name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My first Gifub Actions Job"

        - name: list fields
          run: ls

        - name: Read file
          run: cat README.md